spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/book?useSSL=false
  jpa:
    show-sql: true
logging:
  level:
    cn.edu.ncu.bootjpademo: debug


